### ISSUE TITLE
NLU example utterances

### ISSUE THREAD

**Issue by rgstephens** [CDCgov/covid19healthbot#9]
Are NLU example utterances available?

**Comment by mikesnowkettering** [comment]
Can you provide some more details on your question?  The scenarios posted here are being driven by clicking through explicit prompts more than they are by language models.  Are you talking about examples of how different organizations are using it from Health Bots that have broader applications than just these scenarios and a need to launch them accordingly?

**Comment by rgstephens** [comment]
While the questions all expect yes or no responses, the user could respond with a symptom description, conditions, work location or job, etc. Do you have example utterances for these type of responses?

**Comment by tomsavel** [comment]
Hi.  Great question.  As we're a bit new to this specific bot technology as well, we're going to reach out to Microsoft - and see what we can find out.

**Comment by AdamWalkerMicrosoft** [comment]
NLU is not being leveraged in this implementation, however, more generally the Healthcare Bot supports NLU based on Microsoft LUIS and Microsoft QnA maker. Within the Healthcare Bot the NLU behaves differently based on the context. Broadly speaking there are two types of utterance: 

- **Top level utterance**: An utterance that is typed when there is no active scenario. Essentially the bot is in the root (which is a standby state waiting for initial input). In this case, the end-users utterance is analysed and used to determine which scenario should be triggered (in the CDC implementation this isn't required since there is only a single triage scenario that is invoked on page load).  Usually, you would train a model to understand the intent, for example "I think I have COVID19" could be an utterance that would trigger the COVID19 triage. 
- **Mid scenario utterance**: An utterance that is a response to a question in the scenario. Typically, in this case, no NLU is applied, but there is an attempt to match (even partially) the response to the choice options. If one of the options is not identified, then it will prompt the user to answer again. In more sophisticated implementations you can use "Interrupting" scenarios. These attempt to identify if the end-user is trying to change the topic and cause the bot to break out of the currently active scenario. 

In general, you can find more information about Healthcare Language models here: 
[https://docs.microsoft.com/en-us/HealthBot/language_models](https://docs.microsoft.com/en-us/HealthBot/language_models)
